# Generated by Django 4.2.1 on 2023-05-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pokemon', models.CharField(max_length=40)),
                ('numero', models.IntegerField(max_length=4)),
                ('generacion', models.IntegerField(max_length=2)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
    ]
