# Generated by Django 4.2.1 on 2023-05-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
