# Generated by Django 4.2.1 on 2023-05-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_owner_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
